// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzacBnnWRTzcYdZLePnW_ECbhmUDATGWI',
    appId: '1:518090744579:web:5aa0b33acaa8a99767bf36',
    messagingSenderId: '518090744579',
    projectId: 'movie-t1',
    authDomain: 'movie-t1.firebaseapp.com',
    storageBucket: 'movie-t1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV0PKsaHlxoe5CeYq4NVBVk2_zPY8b7Ls',
    appId: '1:518090744579:android:b183487032f6bdd767bf36',
    messagingSenderId: '518090744579',
    projectId: 'movie-t1',
    storageBucket: 'movie-t1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCID36K4Y20vCbwe0i7LAs6L5L6gcBGpEY',
    appId: '1:518090744579:ios:f3c30673722231c767bf36',
    messagingSenderId: '518090744579',
    projectId: 'movie-t1',
    storageBucket: 'movie-t1.firebasestorage.app',
    iosClientId: '518090744579-j8fg217v1kinojpqbs807l3fnjvldhvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCID36K4Y20vCbwe0i7LAs6L5L6gcBGpEY',
    appId: '1:518090744579:ios:f3c30673722231c767bf36',
    messagingSenderId: '518090744579',
    projectId: 'movie-t1',
    storageBucket: 'movie-t1.firebasestorage.app',
    iosClientId: '518090744579-j8fg217v1kinojpqbs807l3fnjvldhvf.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzacBnnWRTzcYdZLePnW_ECbhmUDATGWI',
    appId: '1:518090744579:web:923bdd7138a5db8c67bf36',
    messagingSenderId: '518090744579',
    projectId: 'movie-t1',
    authDomain: 'movie-t1.firebaseapp.com',
    storageBucket: 'movie-t1.firebasestorage.app',
  );
}
